export const mdxMapping: { [key: string]: string } = {
  '/curriculum/sv-foundations': '/curriculum/sv-foundations/introduction.mdx',
  '/curriculum/sv-foundations/introduction': '/curriculum/sv-foundations/introduction.mdx',
  '/curriculum/sv-foundations/data-types': '/curriculum/sv-foundations/data-types/literals-and-basic-types.mdx',
  '/curriculum/sv-foundations/data-types/literals-and-basic-types': '/curriculum/sv-foundations/data-types/literals-and-basic-types.mdx',
  '/curriculum/sv-foundations/data-types/nets-and-variables-logic-vs-wire': '/curriculum/sv-foundations/data-types/nets-and-variables-logic-vs-wire.mdx',
  '/curriculum/sv-advanced': '/curriculum/sv-advanced/object-oriented-programming/inheritance-polymorphism-virtual-methods.mdx',
  '/curriculum/sv-advanced/object-oriented-programming': '/curriculum/sv-advanced/object-oriented-programming/inheritance-polymorphism-virtual-methods.mdx',
  '/curriculum/sv-advanced/object-oriented-programming/inheritance-polymorphism-virtual-methods': '/curriculum/sv-advanced/object-oriented-programming/inheritance-polymorphism-virtual-methods.mdx',
  '/curriculum/uvm-core': '/curriculum/uvm-core/base-class-library/uvm-object-vs-uvm-component.mdx',
  '/curriculum/uvm-core/base-class-library': '/curriculum/uvm-core/base-class-library/uvm-object-vs-uvm-component.mdx',
  '/curriculum/uvm-core/base-class-library/uvm-object-vs-uvm-component': '/curriculum/uvm-core/base-class-library/uvm-object-vs-uvm-component.mdx',
  '/curriculum/uvm-core/phasing-and-synchronization': '/curriculum/uvm-core/phasing-and-synchronization/the-uvm-phases-in-detail.mdx',
  '/curriculum/uvm-core/phasing-and-synchronization/the-uvm-phases-in-detail': '/curriculum/uvm-core/phasing-and-synchronization/the-uvm-phases-in-detail.mdx',
};
