"use client";

import React, { useMemo, useState } from "react";

import { CodeTrace } from "@/components/visual-system/CodeTrace";
import { VisualFrame } from "@/components/visual-system/VisualFrame";
import { regionGuideById } from "@/components/visuals/scheduler/region-guide";
import { REGION_LABELS, REGION_ORDER, type RegionId } from "@/lib/sv-scheduler-model";
import { REGION_CLAUSES, buildRegionQuiz, type RegionQuizQuestion } from "@/lib/sv-region-map-model";
import { cn } from "@/lib/utils";

/**
 * Questions and answer keys are generated by running the scheduler model
 * (`buildRegionQuiz`), so the key cannot drift from the model the F3B and F3C
 * visuals use. `final` procedures are not offered: they run once at the end
 * of simulation (§9.2.3), not in a time-slot region.
 */
export const QUESTIONS: RegionQuizQuestion[] = buildRegionQuiz();

const ASSUMPTIONS = [
  "Every answer is read from the scheduler model's trace of one time slot (IEEE 1800-2023 §4.4–§4.5), not from a hand-written key.",
  "An event is placed in the region it was scheduled in. Events moved from Inactive, NBA, Re-Inactive or Re-NBA execute in Active or Reactive (§4.5).",
  "Concurrent assertions are not in the model, so the game does not ask about them; F3B and the SVA lessons cover Preponed sampling and Observed evaluation of properties.",
];

type Answer = { questionId: string; picked: string; correct: boolean };

/** Renders `code` spans in a prompt as inline code. */
function PromptText({ text }: { text: string }) {
  return (
    <>
      {text.split("`").map((part, i) =>
        i % 2 === 1 ? (
          <code key={i} className="rounded bg-muted px-1 font-mono text-[0.95em] [font-variant-ligatures:none]">
            {part}
          </code>
        ) : (
          <React.Fragment key={i}>{part}</React.Fragment>
        ),
      )}
    </>
  );
}

function RegionButton({
  region,
  state,
  disabled,
  onPick,
}: {
  region: RegionId;
  state: "idle" | "correct" | "wrong" | "dim";
  disabled: boolean;
  onPick: () => void;
}) {
  const guide = regionGuideById[region];
  const readOnly = guide.family === "readOnly";
  return (
    <button
      type="button"
      onClick={onPick}
      disabled={disabled}
      className={cn(
        "relative flex min-h-[3.25rem] flex-col items-start rounded-lg border px-3 py-2 text-left transition-colors motion-reduce:transition-none focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-default",
        readOnly ? "border-dashed" : "border-solid",
        guide.family === "reactiveSet"
          ? "border-violet-500/50 bg-violet-500/[0.06]"
          : guide.family === "activeSet"
            ? "border-cyan-500/50 bg-cyan-500/[0.06]"
            : guide.family === "observed"
              ? "border-sky-500/50 bg-sky-500/[0.06]"
              : "border-slate-400/60 bg-slate-500/[0.06]",
        state === "idle" && "hover:bg-muted",
        state === "correct" && "border-emerald-500 bg-emerald-500/15",
        state === "wrong" && "border-rose-500 bg-rose-500/15",
        state === "dim" && "opacity-50",
      )}
    >
      <span className="text-sm font-semibold text-foreground">{REGION_LABELS[region]}</span>
      <span className="text-[11px] leading-tight text-muted-foreground">{guide.tag}</span>
      {state === "correct" ? (
        <span className="absolute right-2 top-1.5 text-emerald-700 dark:text-emerald-300" aria-label="correct answer">
          ✓
        </span>
      ) : null}
      {state === "wrong" ? (
        <span className="absolute right-2 top-1.5 text-rose-700 dark:text-rose-300" aria-label="your answer, incorrect">
          ✕
        </span>
      ) : null}
    </button>
  );
}

export default function EventRegionGame() {
  const questions = QUESTIONS;
  const [started, setStarted] = useState(false);
  const [index, setIndex] = useState(0);
  const [answers, setAnswers] = useState<Answer[]>([]);
  const question = questions[index];
  const current = answers.find((a) => a.questionId === question?.id);
  const score = answers.filter((a) => a.correct).length;
  const finished = index >= questions.length;

  const lines = useMemo(() => (question ? question.code.map((l) => ({ text: l.text, key: l.key, owner: l.owner })) : []), [question]);

  const pick = (picked: string) => {
    if (!question || current) return;
    const correct = question.type === "region" ? picked === question.answer : Boolean(question.options.find((o) => o.id === picked)?.correct);
    setAnswers((prev) => [...prev, { questionId: question.id, picked, correct }]);
  };

  const restart = () => {
    setStarted(false);
    setIndex(0);
    setAnswers([]);
  };

  return (
    <VisualFrame
      label="Event region game"
      eyebrow="Game · retrieval practice"
      title="Event Region Scheduler"
      summary="Place each event on the time-slot ladder. Every answer is computed by the same scheduler model as the F3B and F3C visuals."
      fidelity="model"
      assumptions={ASSUMPTIONS}
    >
      {!started ? (
        <div className="space-y-3">
          <p className="text-sm text-muted-foreground">
            {questions.length} events, all nine regions. For each one, pick the region it is scheduled in; one round asks for the order of printed output. Each answer comes with the
            model&apos;s reason.
          </p>
          <button
            type="button"
            onClick={() => setStarted(true)}
            className="inline-flex h-10 items-center rounded-lg bg-cyan-600 px-4 text-sm font-semibold text-white hover:bg-cyan-500 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
          >
            Start Challenge
          </button>
        </div>
      ) : finished ? (
        <div className="space-y-4" aria-live="polite">
          <p className="text-2xl font-bold text-foreground">
            {score} / {questions.length}
          </p>
          <p className="text-sm text-muted-foreground">
            {score === questions.length ? "Every event placed correctly." : "Review the ones you missed against the ladder in F3B, then play again."}
          </p>
          <ol className="space-y-1 text-sm" aria-label="Your answers">
            {questions.map((q) => {
              const a = answers.find((x) => x.questionId === q.id);
              const right = q.type === "region" ? REGION_LABELS[q.answer] : "the model's log order";
              return (
                <li key={q.id} className="flex gap-2">
                  <span aria-hidden className={a?.correct ? "text-emerald-700 dark:text-emerald-300" : "text-rose-700 dark:text-rose-300"}>
                    {a?.correct ? "✓" : "✕"}
                  </span>
                  <span>
                    <span className="sr-only">{a?.correct ? "Correct: " : "Missed: "}</span>
                    <PromptText text={q.prompt} /> → <strong>{right}</strong>
                  </span>
                </li>
              );
            })}
          </ol>
          <button
            type="button"
            onClick={restart}
            className="inline-flex h-10 items-center rounded-lg border border-border/70 px-4 text-sm font-medium hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
          >
            Play Again
          </button>
        </div>
      ) : (
        <div className="space-y-4">
          <div className="flex flex-wrap items-center justify-between gap-2 font-mono text-xs text-muted-foreground">
            <span>
              Question {index + 1}/{questions.length}
            </span>
            <span>Score: {score}</span>
          </div>
          <CodeTrace label={question.title} lines={lines} activeKey={question.focusKey} />
          <p className="text-sm font-semibold text-foreground">
            <PromptText text={question.prompt} />
          </p>

          {question.type === "region" ? (
            <div role="group" aria-label="Scheduling regions, in time-slot order" className="grid gap-2 grid-cols-[repeat(auto-fit,minmax(min(100%,140px),1fr))]">
              {REGION_ORDER.map((region) => (
                <RegionButton
                  key={region}
                  region={region}
                  disabled={Boolean(current)}
                  onPick={() => pick(region)}
                  state={!current ? "idle" : region === question.answer ? "correct" : region === current.picked ? "wrong" : "dim"}
                />
              ))}
            </div>
          ) : (
            <div role="group" aria-label="Possible logs" className="grid gap-2">
              {question.options.map((o) => (
                <button
                  key={o.id}
                  type="button"
                  disabled={Boolean(current)}
                  onClick={() => pick(o.id)}
                  className={cn(
                    "rounded-lg border border-border/70 px-3 py-2 text-left font-mono text-xs [font-variant-ligatures:none] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-default",
                    !current && "hover:bg-muted",
                    current && o.correct && "border-emerald-500 bg-emerald-500/15",
                    current && !o.correct && current.picked === o.id && "border-rose-500 bg-rose-500/15",
                    current && !o.correct && current.picked !== o.id && "opacity-50",
                  )}
                >
                  {current && o.correct ? <span aria-label="correct answer">✓ </span> : null}
                  {current && !o.correct && current.picked === o.id ? <span aria-label="your answer, incorrect">✕ </span> : null}
                  {o.label}
                </button>
              ))}
            </div>
          )}

          {current ? (
            <div
              aria-live="polite"
              className={cn(
                "space-y-2 rounded-lg border p-3 text-sm",
                current.correct ? "border-emerald-500/50 bg-emerald-500/10" : "border-rose-500/50 bg-rose-500/10",
              )}
            >
              <p className={cn("font-semibold", current.correct ? "text-emerald-800 dark:text-emerald-200" : "text-rose-800 dark:text-rose-200")}>
                {current.correct
                  ? "Correct!"
                  : question.type === "region"
                    ? `Not quite. It lands in ${REGION_LABELS[question.answer]}.`
                    : "Not quite."}
              </p>
              {question.type === "region" ? (
                <>
                  {!current.correct ? (
                    <p className="text-foreground">
                      You picked {REGION_LABELS[current.picked as RegionId]}, which holds: {regionGuideById[current.picked as RegionId].holds}
                    </p>
                  ) : null}
                  <p className="text-foreground [font-variant-ligatures:none]">
                    <strong>Why: </strong>
                    {question.why}
                    {question.delta > 0 ? ` (This happens at Δ ${question.delta}: the scheduler has already gone back to an earlier region in this slot.)` : ""}
                  </p>
                  <p className="text-xs text-muted-foreground">
                    {REGION_LABELS[question.answer]} ({REGION_CLAUSES[question.answer]}): {regionGuideById[question.answer].holds}
                  </p>
                </>
              ) : (
                <>
                  {!current.correct ? <p className="text-foreground">{question.options.find((o) => o.id === current.picked)?.feedback}</p> : null}
                  <p className="text-foreground">
                    <strong>Why: </strong>
                    {question.options.find((o) => o.correct)?.feedback}
                  </p>
                </>
              )}
              <button
                type="button"
                onClick={() => setIndex((i) => i + 1)}
                className="inline-flex h-10 items-center rounded-lg border border-border/70 bg-background/60 px-4 text-sm font-medium hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
              >
                {index + 1 < questions.length ? "Next question" : "See results"}
              </button>
            </div>
          ) : null}
        </div>
      )}
    </VisualFrame>
  );
}
